package hms;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextArea;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import javax.swing.JPasswordField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class DoctorPanel extends javax.swing.JFrame {

    /*
     * Creates new
     * form DoctorPanel
     */

    public DoctorPanel() {
        initComponents();
    }

    /*
     * 
     * This method
     * is called
     * from within
     * the constructor
     * to initialize
     * the form.*WARNING:
     * Do NOT modify this
     * code. The content of this
     * method is always*
     * regenerated by
     * the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 14));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 14));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel19.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel20 = new javax.swing.JLabel();
        jLabel20.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel23 = new javax.swing.JLabel();
        jLabel23.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel1.setText("Name:");

        jLabel3.setText("Contact:");

        jLabel4.setText("Specialization");

        jLabel5.setText("Qualifications:");

        jLabel9.setText("Experience:");

        jLabel12.setText("Consultation Day:");

        JTextArea textAreaName = new JTextArea();
        textAreaName.setEditable(false);

        JTextArea textAreaContact = new JTextArea();
        textAreaContact.setEditable(false);

        JTextArea textAreaSpec = new JTextArea();
        textAreaSpec.setEditable(false);

        textAreaQuali = new JTextArea();
        textAreaQuali.setEditable(false);

        textAreaExperi = new JTextArea();
        textAreaExperi.setEditable(false);

        textAreaConsult = new JTextArea();
        textAreaConsult.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 67,
                                                                GroupLayout.PREFERRED_SIZE))
                                                .addGap(39)
                                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
                                                        .addComponent(textAreaName, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(textAreaContact, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
                                                .addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 73,
                                                                GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(ComponentPlacement.RELATED, 33,
                                                                Short.MAX_VALUE)
                                                        .addComponent(textAreaSpec, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE))
                                                .addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(ComponentPlacement.RELATED,
                                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(textAreaQuali, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE))
                                                .addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 78,
                                                                GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(ComponentPlacement.RELATED,
                                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(textAreaExperi, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE))
                                                .addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 102,
                                                                GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(ComponentPlacement.RELATED)
                                                        .addComponent(textAreaConsult, GroupLayout.PREFERRED_SIZE, 200,
                                                                GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(906, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 19,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textAreaName, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(textAreaContact, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 19,
                                                GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 22,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textAreaSpec, GroupLayout.PREFERRED_SIZE, 25,
                                                GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 24,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textAreaQuali, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(textAreaExperi, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18)
                                .addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(textAreaConsult, GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(317, Short.MAX_VALUE)));
        jPanel4.setLayout(jPanel4Layout);

        jTabbedPane2.addTab("My Information", jPanel4);

        jLabel14.setText("Name:");

        jLabel16.setText("Contact:");

        jLabel17.setText("Specialization:");

        jLabel18.setText("Qualifications:");

        jLabel22.setText("Experience:");

        jLabel25.setText("Consultation Day:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btnNewButton_1 = new JButton("Change");
        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(30)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.TRAILING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel22, GroupLayout.PREFERRED_SIZE, 70,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addGap(22)
                                                .addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 109,
                                                        Short.MAX_VALUE)
                                                .addGap(53)
                                                .addComponent(jLabel25, GroupLayout.PREFERRED_SIZE, 102,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 71,
                                                        GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 88,
                                                                        GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextField7))
                                                        .addGroup(Alignment.TRAILING, jPanel7Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel7Layout
                                                                        .createParallelGroup(Alignment.TRAILING)
                                                                        .addComponent(jLabel17,
                                                                                GroupLayout.PREFERRED_SIZE, 92,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addComponent(jLabel14,
                                                                                        GroupLayout.PREFERRED_SIZE, 37,
                                                                                        GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18))
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addComponent(jLabel16,
                                                                                        GroupLayout.PREFERRED_SIZE, 55,
                                                                                        GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18)))
                                                                .addGroup(jPanel7Layout
                                                                        .createParallelGroup(Alignment.LEADING)
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addPreferredGap(
                                                                                        ComponentPlacement.RELATED, 7,
                                                                                        Short.MAX_VALUE)
                                                                                .addGroup(jPanel7Layout
                                                                                        .createParallelGroup(
                                                                                                Alignment.LEADING)
                                                                                        .addComponent(jTextField1,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                170,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jTextField2)))
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addPreferredGap(
                                                                                        ComponentPlacement.UNRELATED)
                                                                                .addComponent(jTextField3,
                                                                                        GroupLayout.PREFERRED_SIZE, 173,
                                                                                        GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(150)))
                                .addGap(316))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(235)
                                .addComponent(btnNewButton_1)
                                .addContainerGap(453, Short.MAX_VALUE)));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(67)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 33,
                                                GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                .addGap(25)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 22,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(27)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(18)
                                .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel25)
                                        .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22))
                                .addGap(41)
                                .addComponent(btnNewButton_1)
                                .addContainerGap(91, Short.MAX_VALUE)));
        jPanel7.setLayout(jPanel7Layout);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 727, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 514, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));

        jTabbedPane2.addTab("Update Information", jPanel5);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("New Password");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Confirm Password");
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Old Password");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JButton btnNewButton = new JButton("Change Password");
        btnNewButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

            }
        });
        btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 17));

        passwordField = new JPasswordField();

        passwordField_1 = new JPasswordField();

        passwordField_2 = new JPasswordField();
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(30)
                                .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(jLabel20, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                        .addComponent(jLabel23, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false)
                                                .addComponent(passwordField_1, GroupLayout.DEFAULT_SIZE, 420,
                                                        Short.MAX_VALUE)
                                                .addComponent(passwordField))
                                        .addComponent(passwordField_2, GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                                .addGap(612))
                        .addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(268)
                                .addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(765, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(37)
                                .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(jLabel23, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(passwordField, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addGap(26)
                                .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
                                        .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(passwordField_1, GroupLayout.PREFERRED_SIZE, 35,
                                                GroupLayout.PREFERRED_SIZE))
                                .addGap(18)
                                .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false)
                                        .addComponent(jLabel20, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(passwordField_2, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addGap(60)
                                .addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                                .addGap(287)));
        jPanel6.setLayout(jPanel6Layout);

        jTabbedPane2.addTab("Change Password", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane2)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane2)
                                .addContainerGap()));

        jTabbedPane1.addTab("Account", jPanel1);
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 739, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 557, Short.MAX_VALUE));

        jTabbedPane1.addTab("See Appointment", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 739, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 557, Short.MAX_VALUE));

        jTabbedPane1.addTab("History", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField7ActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private JTextArea textAreaQuali;
    private JTextArea textAreaExperi;
    private JTextArea textAreaConsult;
    private JPasswordField passwordField;
    private JPasswordField passwordField_1;
    private JPasswordField passwordField_2;
    private JButton btnNewButton_1;

}